version: '3.9'
services:
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    networks:
       - backend
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
    db:
      driver: local


networks:
  backend: 