// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"rest-api/api"
	"rest-api/repo"
	"rest-api/service"
)

// Injectors from wire.go:

func initApi() api.HiAPI {
	hiRepo := repo.NewRepo()
	hiService := service.NewService(hiRepo)
	hiAPI := api.NewApi(hiService)
	return hiAPI
}
