// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IApi is an autogenerated mock type for the IApi type
type IApi struct {
	mock.Mock
}

// SayHi provides a mock function with given fields: c
func (_m *IApi) SayHi(c *gin.Context) {
	_m.Called(c)
}

// NewIApi creates a new instance of IApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *IApi {
	mock := &IApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
