// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	dto "rest-api/dto"

	mock "github.com/stretchr/testify/mock"
)

// IHiService is an autogenerated mock type for the IHiService type
type IHiService struct {
	mock.Mock
}

// SayHi provides a mock function with given fields:
func (_m *IHiService) SayHi() dto.MyMessage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SayHi")
	}

	var r0 dto.MyMessage
	if rf, ok := ret.Get(0).(func() dto.MyMessage); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.MyMessage)
	}

	return r0
}

// NewIHiService creates a new instance of IHiService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHiService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHiService {
	mock := &IHiService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
